name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: docker build -t dev-course .

      - name: Run Docker container
        run: docker run -d -p 8000:8000 dev-course
